language: ruby # Defaults to ruby, but travis-ci recommends making this explicit.
rvm:
  - 2.0.0
  - 2.1.2
go:
  - 1.1
env: DB=postgres CI=1
bundler_args: --without development debug
before_install: 
  - git clone git://github.com/redis/hiredis.git && cd hiredis && make && sudo make install && sudo ldconfig && cd ..
before_script:
  - cp config/database.yml.ci config/database.yml
  - cp config/app_config.yml.example config/app_config.yml
  - echo "foo" > mail_username.txt
  - echo "bar" > mail_password.txt
  - echo "f7264dd590e09007703723a75550c748" > secret_token
  - psql -c 'create database snpr_test;' -U postgres
# script: "bundle install" # this is automatically run by travis-ci
services:
  - redis-server
script: "bundle exec rake --trace go_worker:build db:migrate test"

