language: ruby # Defaults to ruby, but travis-ci recommends making this explicit.
sudo: false
cache: bundler
addons:
  apt:
    packages:
    - libhiredis-dev
  postgresql: "9.2"
services:
  - redis-server
rvm:
  - 2.2.0
env: DB=postgres CI=1
bundler_args: --without development debug
before_script:
  - cp config/database.yml.ci config/database.yml
  - cp config/app_config.yml.example config/app_config.yml
  - echo "foo" > mail_username.txt
  - echo "bar" > mail_password.txt
  - echo "secret-token" > secret_token
  - echo "secret-key-base" > secret_key_base
  - psql -c 'create database snpr_test;' -U postgres
  - bundle exec rake db:setup
script: "bundle exec rake test"
